image: python:latest

stages:
  - verify

verify:
  script:
    - pip install black isort[colors] pycodestyle
    - black . --check --diff --color
    - isort . --check-only --diff --color
    - pycodestyle --config=setup.cfg .
  stage: verify
  only:
    - merge_requests
